#! /bin/sh

# things to launch at start of wm
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# window rules
bspc rule -a Gimp desktop='^7' state=floating follow=on
bspc rule -a Brave-browser desktop='^10' follow=on
bspc rule -a librewolf desktop='^10' follow=on
bspc rule -a qutebrowser follow=on #desktop='^9' 
bspc rule -a Emacs state=tiled # desktop='^9' follow=on
bspc rule -a discord state=tiled desktop='^3' follow=on
bspc rule -a mpv state=tiled desktop='^4' follow=on
bspc rule -a Zathura state=tiled

# colors
bspc config normal_border_color "#4C566A"
bspc config active_border_color "#A3BE8C"
bspc config focused_border_color "#88c0d0"
bspc config presel_feedback_color "#434C5E"
